# Generated by Django 4.2.15 on 2024-09-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_joining',
            field=models.BooleanField(default=False),
        ),
    ]
