# Generated by Django 4.2.15 on 2024-09-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_player_is_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='newusername',
            field=models.CharField(default='', max_length=100),
        ),
    ]
